all:
	gcc -Wall -pedantic -Werror -Wextra -c src/absolute.c src/cap_string.c src/contact_strings.c src/first_digit.c src/is_prime_number.c src/lowercase.c src/nconcat_strings.c src/positive_or_not.c src/power.c src/print_array.c src/print_number.c src/print_string.c src/reverse_array.c src/reverse_string.c src/square_root.c src/str_len.c src/string_copy.c src/string_ncopy.c src/string_to_integer.c src/strings_compare.c src/swap_int.c src/uppercase_string.c src/uppercase.c
	ar -rc libholbertonschool.a absolute.o cap_string.o contact_strings.o first_digit.o is_prime_number.o lowercase.o nconcat_strings.o positive_or_not.o power.o print_array.o print_number.o print_string.o reverse_array.o reverse_string.o square_root.o str_len.o string_copy.o string_ncopy.o string_to_integer.o strings_compare.o swap_int.o uppercase_string.o uppercase.o
	rm absolute.o cap_string.o contact_strings.o first_digit.o is_prime_number.o lowercase.o nconcat_strings.o positive_or_not.o power.o print_array.o print_number.o print_string.o reverse_array.o reverse_string.o square_root.o str_len.o string_copy.o string_ncopy.o string_to_integer.o strings_compare.o swap_int.o uppercase_string.o uppercase.o
clean:
	rm libholbertonschool.a
re: all
